name: Train and Commit Model

on:
  push:
    paths:
      - model.py
      - .github/workflows/train.yml

jobs:
  train-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Required for committing

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run training script
      run: python model.py

     - name: Commit and push model.pkl
       run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add model/model.pkl
        git commit -m "Auto-commit: updated model.pkl" || echo "No changes to commit"
        
        # Set the Git remote URL with GITHUB_TOKEN
         git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
   
         # Push the changes
         git push origin HEAD:${{ github.ref }}
